### ISSUE TITLE
Please add samples

### ISSUE THREAD

**Issue by ghost** [smack0007/GLFWDotNet#1]
I'm considering using this in one of my projects but I'd really love to see some samples first.

Could you make a few samples showing this off with source code and screenshots?

Thanks :)

**Comment by ghost** [comment]
Nvm, found them. Sorry.

Could you make them more visible to newcomers on this repo?
I didn't immediately find it and had to do some digging to find it.

**Comment by ghost** [comment]
Also, could you make downloading them easier so that people don't have to download the entire repo just to check out the samples?

**Comment by smack0007** [comment]
I'll put a link in the description that says where to find the Samples. As far as not having to download the repo I'll need to have some kind of proper release strategy in place beforehand.

Ideas are welcome of course.

**Comment by ghost** [comment]
Cool cool. I'll close this.
