### ISSUE TITLE
Possible to use GLAD to load OpenGL in C#

### ISSUE THREAD

**Issue by GeorgeS2019** [smack0007/GLFWDotNet#17]
Is it possible to combine [OpenGL.NET](https://www.nuget.org/packages/OpenGL.Net) together with GLFWDotNET so it is possible to load OpenGL without needing to create the delegate for each OpenGL call?

https://github.com/Dav1dde/glad
https://github.com/Dav1dde/glad/blob/master/example/c%2B%2B/hellowindow2.cpp
```c++
    // Register callback functions
    glfwSetFramebufferSizeCallback(g_window, framebufferSizeCallback);
    glfwSetScrollCallback(g_window, scrollCallback);

    // Loading OpenGL function pointers
    if (!gladLoadGLLoader(reinterpret_cast<GLADloadproc>(glfwGetProcAddress)))
    {
        std::cerr << "Failed to load OpenGL context" << std::endl;
        return -1;
    }`

**Comment by smack0007** [comment]
I've never used OpenGL.NET but I would assume it should be possible to use it with GLFWDotNet as it just wants a window handle. GLAD doesn't seem to generate C# code as far as I can see.

Take a look at my [GLDotNet](https://github.com/smack0007/GLDotNet) project. There I load all the GL functions based on the version provided. I'm sure OpenGL.NET does something similar.
